### ISSUE TITLE
Kamailio decrypting TLS / SRTP Voipmonitor Sniffer

### ISSUE THREAD

**Issue by dcisnerostff** [voipmonitor/sniffer#106]
Hello,

I have a Kamailio server with voipmonitor sniffer installed.

I uncommented the SSL / SRTP options in the voipmonitor.conf file. But my calls are only showing one leg of the call that is already decrypted, it isn't showing me the SRTP portion of the call unless I edit the Kamailio.cfg file when adding siptrace module for duplicate uri

modparam("siptrace", "duplicate_uri", "sip:X.X.X.X:5061")

I am referencing this wiki guide: https://www.voipmonitor.org//doc/Tls#Kamailio 

Tried both the Kamailio steps and the generic steps but still don't see any SRTP calls showing up on my host VoIPmonitor.

I use the new client/server set-up with packetbuffer_sender = yes so it sends all RAW data to the host Voipmonitor for processing. 

May I have any assistance getting Voipmonitor to decrypt my calls running through Kamailio?

**Comment by voipmonitor** [comment]
Hi, please write to the support@voipmonitor.org
