### ISSUE TITLE
SSLKEYLOG WITH_TCP Undefined Symbol Error

### ISSUE THREAD

**Issue by SkyVera** [voipmonitor/sniffer#110]
Hi,

I am trying to install SSLKEYLOG tool for Kamailio and Freeswitch.

It works as UDP, but when I try to use it as TCP, it gives the error "undefined symbol: resolver".

Do you have a solution or fix for this?

```
env SSLKEYLOG_TCP='127.0.0.1:1234' LD_PRELOAD="/usr/local/src/voipmonitor-git/tools/ssl_keylogger/sslkeylog.so" /usr/local/sbin/kamailio
/usr/local/sbin/kamailio: symbol lookup error: /usr/local/src/voipmonitor-git/tools/ssl_keylogger/sslkeylog.so: undefined symbol: resolver
```

It's also built as `make with_tcp`

Kamailio version: 5.4.2
FreeSWITCH version: 1.10.3

**Comment by milon21** [comment]
Hello,

hmm probably problem with build process, can you try:

make clean
make with_tcp

Thanks.

Best regards.

**Comment by SkyVera** [comment]
Hello,

yes this solved my problem thank you :)
