### ISSUE TITLE
Configuration file comments don't match the code

### ISSUE THREAD

**Issue by suiyuemanbu** [voipmonitor/sniffer#111]
in voipmonitor.conf:
 The maximum number of threads is capped at **9**, even if a higher value is configured.
#mysqlstore_max_threads_cdr = 2

but in sniffer-master\voipmonitor.cpp
if((value = ini.GetValue("general", "mysqlstore_max_threads_cdr", NULL))) {
		opt_mysqlstore_max_threads_cdr = max(min(atoi(value), **99**), 1);
}

Which one is right? Please revise it.

**Comment by voipmonitor** [comment]
it is 99. Fixed in .conf now.
