### ISSUE TITLE
RTP packets are not being written to pcap files

### ISSUE THREAD

**Issue by csiwek** [voipmonitor/sniffer#18]
Hi,

We are testing the sniffer for some time now. We've got set:
savertp=yes
pcapsplit=no

For some reason only SIP packets are being written to the pcap file. If we switch to pcapsplit=yes, sniffer writes SIP and RTP to the separate files. Am I missing something or it's a bug?

**Comment by voipmonitor** [comment]
Hi this seems like bug but - why do you need pcapsplit = no ?

2015-08-21 17:08 GMT+02:00 Cezary <notifications@github.com>:

> Hi,
>
> We are testing the sniffer for some time now. We've got set:
> savertp=yes
> pcapsplit=no
>
> For some reason only SIP packets are being written to the pcap file. If we
> switch to pcapsplit=yes, sniffer writes SIP and RTP to the separate files.
> Am I missing something or it's a bug?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/voipmonitor/sniffer/issues/18>.
>



-- 
Best regards
Martin Vit

**Comment by csiwek** [comment]
having  SIP and RTP in one pcap file suits us more. We don't use the frontend, we just store files and records in the DB for very short time. 
I also noticed that even with pcap_dump_zip=yes and pcapsplit=no , files stay uncompressed.

**Comment by voipmonitor** [comment]
Hi,

please update to the latest git which fixes rtp recording when LZO is
missing or run ./configure (everytime you update git it is better to run
./configure to update your Makefile)

2015-08-21 19:23 GMT+02:00 Cezary <notifications@github.com>:

> having SIP and RTP in one pcap file suits us more. We don't use the
> frontend, we just store files and records in the DB for very short time.
> I also noticed that even with pcap_dump_zip=yes and pcapsplit=no , files
> stay uncompressed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/voipmonitor/sniffer/issues/18#issuecomment-133502985>.
>



-- 
Best regards
Martin Vit
