### ISSUE TITLE
Who is actually cleaning pool?

### ISSUE THREAD

**Issue by glukinho** [voipmonitor/sniffer#19]
Hi,

In /etc/voipmonitor.conf I set some options regarding maxpoolsize and maxpooldays:
```
maxpoolsize = 61440
maxpooldays = 7
```

But my files remain for more than 7 days and take hdd space.

What I actually need to have my files cleaned regularly - running voipmonitor service only or some actions defined in crontab? What process manages files?

Thanks.

**Comment by voipmonitor** [comment]
Hello this should do it if not try to reindex your files with "echo reindexfiles | nc localhost 5029" 
cleaning is done by the voipmonitor process itself.

**Comment by glukinho** [comment]
Thanks for the reply.

I have a bit more complex environment, two sniffers on two servers are separated from files (files are stored in the third server without running sniffer at all). Files are transferred to SRV3 via sshfs. Please see the diagram: ![default](https://cloud.githubusercontent.com/assets/15836211/11211010/5c0d31fe-8d3d-11e5-979b-6f8dc88a1cf7.JPG)

I use maxpoolsize and maxpooldays on both SRV1 and SRV2. Is it right? Will they conflict when cleaning the same file storage?

Is it possible to manage the storage that attached remotely via sshfs? Or I have to setup another sniffer on SRV3?

**Comment by voipmonitor** [comment]
Do they share the same folder or separate folder? The latest versions cant share the same folder and you need to set cleaning on both separately 

#set default maxpoolsize to 100 GB (102400 MB) 
maxpoolsize             = 102400
maxpooldays            =  

maxpoolsipsize         =
maxpoolsipdays         = 

maxpoolrtpsize         =
maxpoolrtpdays         =  

maxpoolgraphsize       =
maxpoolgraphdays       =

maxpoolaudiosize       =
maxpoolaudiodays       =

**Comment by glukinho** [comment]
They share the same folder. I use sniffer version 11.9, what about it?

**Comment by voipmonitor** [comment]
once you will have .tar or .tar.gz files in spool which is since 12.X I think you cannot share the same folder

**Comment by glukinho** [comment]
What does it mean? I cannot move files from multiple sniffers into one folder? Or I have to run voipmonitor service on SRV3 and clean files only from SRV3?

Another question is, when the cleaning happens actually? At fixed time once a day? Or progressively through the whole day?

**Comment by voipmonitor** [comment]
No you cannot in the latest sniffers. You need to have separate folders for each sniffer on central storage. Cleaning is progressively cleaning every hour which is resolution of the cleaning procedure (cannot be shorter)

**Comment by glukinho** [comment]
You mean I should use this option, right?
```
# enables writing pcap files to separate folders per sensor id or sensor name. Enable this feature only if you are not using database. 
# spooldir_by_sensorname = yes
# name_sensor = sensor1
```

**Comment by voipmonitor** [comment]
no this is only for case where you have one receiver and multiple sender (mirroring)

**Comment by glukinho** [comment]
OK, thanks a lot for your answers.
