### ISSUE TITLE
voipmonitor binary calls gethostbyname()

### ISSUE THREAD

**Issue by deadpoint** [voipmonitor/sniffer#21]
Another rpmlint warning produced by the open build service checks.

[  133s] voipmonitor.x86_64: I: binary-or-shlib-calls-gethostbyname /usr/sbin/voipmonitor
[  133s] The binary calls gethostbyname(). Please port the code to use getaddrinfo().

**Comment by voipmonitor** [comment]
ignore the warning until we get time to do the convert.
