### ISSUE TITLE
Voipmonitor is crashing

### ISSUE THREAD

**Issue by JavaMachine** [voipmonitor/sniffer#23]
Hello fellow developers...

I have followed the instructions and successfully installed voipmaster:
https://github.com/voipmonitor/sniffer/blob/develop/README.debian

But the problem is, it seems voipmonitor is crashing after start...
![image](https://cloud.githubusercontent.com/assets/5568121/11694111/1833d5e8-9eca-11e5-872e-ed1dfecce74b.png)

Where and what I might did wrong? Where I can find logs?

**Comment by voipmonitor** [comment]
Hi - please check syslog (/var/log/messages or /var/log/syslog) what you
see? You can also write me on support@voipmonitor.org

2015-12-09 19:12 GMT+01:00 JavaMachine <notifications@github.com>:

> Hello fellow developers...
>
> I have followed the instructions and successfully installed voipmaster:
> https://github.com/voipmonitor/sniffer/blob/develop/README.debian
>
> But the problem is, it seems voipmonitor is crashing after start...
> [image: image]
> <https://cloud.githubusercontent.com/assets/5568121/11694111/1833d5e8-9eca-11e5-872e-ed1dfecce74b.png>
>
> Where and what I might did wrong? Where I can find logs?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/voipmonitor/sniffer/issues/23>.
>



-- 
Best regards
Martin Vit

**Comment by JavaMachine** [comment]
Oh... now I see the problem... Thank you for quick reply...

Dec  9 13:09:33 SwiperF voipmonitor[25570]: set buffer memory limit to 2072719360
Dec  9 13:09:33 SwiperF voipmonitor[25570]: set buffer memory limit to 2072719360
Dec  9 13:09:33 SwiperF voipmonitor[25570]: start voipmonitor version 14.4.2
Dec  9 13:09:33 SwiperF voipmonitor[25570]: local time 2015-12-09 13:09:33
Dec  9 13:09:33 SwiperF voipmonitor[25570]: for rrd graph you need install rrdtool
Dec  9 13:09:33 SwiperF voipmonitor[25576]: query error in [SET GLOBAL max_allowed_packet=1024*1024*100]:  1227 - Access denied; you need (at least one of) the SUPER privilege(s) for this operation
Dec  9 13:09:33 SwiperF voipmonitor[25576]: Query for set / get max allowed packet size failed. Concat query size is limited. Please set max_allowed_packet to 100MB manually in your mysql configuration file.
Dec  9 13:09:33 SwiperF voipmonitor[25576]: query error in [CREATE DATABASE IF NOT EXISTS `voipmonitor`]:  1044 - Access denied for user 'java'@'%' to database 'voipmonitor'
Dec  9 13:09:33 SwiperF voipmonitor[25576]: query error in [USE `voipmonitor`]:  1044 - Access denied for user 'java'@'%' to database 'voipmonitor'
Dec  9 13:09:33 SwiperF voipmonitor[25576]: connect - db version 5.5
Dec  9 13:09:34 SwiperF voipmonitor[25576]: query error in [SET GLOBAL max_allowed_packet=1024*1024*100]:  1227 - Access denied; you need (at least one of) the SUPER privilege(s) for this operation
Dec  9 13:09:34 SwiperF voipmonitor[25576]: Query for set / get max allowed packet size failed. Concat query size is limited. Please set max_allowed_packet to 100MB manually in your mysql configuration file.
Dec  9 13:09:34 SwiperF voipmonitor[25576]: query error in [SET GLOBAL innodb_file_per_table=1;]:  1227 - Access denied; you need (at least one of) the SUPER privilege(s) for this operation
Dec  9 13:09:34 SwiperF voipmonitor[25576]: query error in [CREATE DATABASE IF NOT EXISTS `voipmonitor`]:  1044 - Access denied for user 'java'@'%' to database 'voipmonitor'
Dec  9 13:09:34 SwiperF voipmonitor[25576]: query error in [USE `voipmonitor`]:  1044 - Access denied for user 'java'@'%' to database 'voipmonitor'
Dec  9 13:09:34 SwiperF voipmonitor[25576]: connect - db version 5.5
Dec  9 13:09:35 SwiperF voipmonitor[25576]: query error in [USE `voipmonitor`]:  1044 - Access denied for user 'java'@'20 database 'voipmonitor' - exit!
