### ISSUE TITLE
RTP pcapsplit errors ?

### ISSUE THREAD

**Issue by Antoineb2s** [voipmonitor/sniffer#25]
Hi,

I'm using the last git sniffer version.
I want to split RTP and SIP pcap by enabling : 

pcap_dump_zip = yes
pcap_dump_ziplevel_sip = 6
pcap_dump_zip_rtp = lzo
tar = yes
tar_maxthreads = 8
tar_compress_sip = gzip
tar_sip_level = 6
tar_compress_rtp = lzo
tar_rtp_level = 1
pcapsplit = yes

No problem for SIP pcap, but for rtp, in the tar file I have several rtp files, for exemple : 

0770afa6a216425d8fc8b7ae448a0d02.pcap
0770afa6a216425d8fc8b7ae448a0d02.pcap#1
0770afa6a216425d8fc8b7ae448a0d02.pcap#3
0770afa6a216425d8fc8b7ae448a0d02.pcap#5
0770afa6a216425d8fc8b7ae448a0d02.pcap#7
0770afa6a216425d8fc8b7ae448a0d02.pcap#9

When I try to open the first pcap, Wireshark says :
"The file 0770afa6a216425d8fc8b7ae448a0d02.pcap isn't a capture file in a format Wireshark understands." 
The strange thing is that I can open the second one finishing by #1, BUT remains error "The capture file appears to have been cut short in the middle of a packet."

I don't know what to do with the others files.

Is this the right behaviour of the RTP spliting ? How to get rid of these issues ?

I also noticed that when setting pcapsplit = no , the pcap file format seems to be correct for wireshirk but don't be compressed in a tar file ?

Thanks for your help.

**Comment by voipmonitor** [comment]
Hi, the first is #1 then it goes with #3,#5 etc and the last one is .pcap - concatenate it with this order. Also take in mind that they are compressed with LZO so you have to unlzo it after concatenate.

**Comment by Antoineb2s** [comment]
Which tool do you use for concatenate thes files ?

**Comment by voipmonitor** [comment]
any tool which can join files. You can also turn off the tar feature by setting tar = no

**Comment by Antoineb2s** [comment]
Thanks for your reply :)

Lot of manual actions needed I guess... :p

Is it possible to save SIP pcap only and ask to the sniffer to save rtp without a restart ?

**Comment by voipmonitor** [comment]
:) yes through capture rules which are stored in mysql so you can have savertp = no and add capture rule which anables rtp storing only for some calls based on ip/tel etc.
