### ISSUE TITLE
VoIPmonitor process down again and again

### ISSUE THREAD

**Issue by Qarar** [voipmonitor/sniffer#27]
Hi There,

The voipmonitor process is down again and again on centos7.How i can trace this problem?I really appreciate this if you help me

Thanks
ALi

**Comment by voipmonitor** [comment]
Can you please write me to support@voipmonitor.org - ideally with ssh access information so we can debug it

**Comment by Qarar** [comment]
sure

**Comment by voipmonitor** [comment]
fixed
