### ISSUE TITLE
WebRTC

### ISSUE THREAD

**Issue by qmex-mp** [voipmonitor/sniffer#28]
There is something about WebRTC Monitoring in the Source, but nothing in the Documentation and nothing in the Config File. Is there a Reason?

**Comment by voipmonitor** [comment]
Hi this is some specific feature for one of our customer which is not possible to apply for others. Anyway - the feature takes http traffic and stores it to http_* tables. The GUI can then pare them with SIP messages through special http headers. If you are interested in this let me know on support@voipmonitor.org

**Comment by a-illiushchenia** [comment]
Good day! Can sniffes process WEBRtс? If it can, could you give documentation link?

**Comment by voipmonitor** [comment]
Hi, 

see http://www.voipmonitor.org/doc/Webrtc

**Comment by a-illiushchenia** [comment]
> Hi,
> 
> see http://www.voipmonitor.org/doc/Webrtc

Thankyou! Maybi you can say what meen TLS server in this config of sniffer:

> ############## SIP TLS SSL SUPPORT
> #if you want to decrypt TLS encrypted SIP you need to enable ssl = yes and pprovide options for ssl_ipport where 10.0.0.1 is IP address of your
> #TLS server 5061 is TCP port and your.key contains private key
> #ssl_ipport detects websocket over SSL / TCP (webrtc)
> #note that you cannot decrypt TLS where you use cipher suite with diffie hellman key exchange by nature. 
>  
> #ssl = yes
> #ssl_ipport = 10.0.0.1 : 5061 /path/to/your.key

**Comment by voipmonitor-petr** [comment]
Hello,
TLS server is server that sends packet "server hello" for key/cert xchange

**Comment by a-illiushchenia** [comment]
> Hello,
> TLS server is server that sends packet "server hello" for key/cert xchange

Thankyou!
