### ISSUE TITLE
Doesn't compile on FreeBSD

### ISSUE THREAD

**Issue by wolrah** [voipmonitor/sniffer#37]
Following the instructions in README.freebsd on a fresh copy of the FreeBSD-provided VHD for FreeBSD-10.3-RELEASE I have yet to produce a usable binary.

Among other things, "lzo2" should be added to the list of packages to install, use of malloc.h instead of stdlib.h creates an error, malloc_trim() doesn't exist outside of glibc.

I am currently trying to bodge my way through it to see if I can make something useful build but I'm running in to a lot of "error: declaration of 'HeapSafeCheck' has a different language linkage" in the jitter buffer code which isn't making sense to me because your extern "C" entries seem to be where they need to be.  I'm by no means familiar with integrating C and C++ code though so I'm just going by Google and guessing here.

**Comment by voipmonitor** [comment]
Hi we have no resources currently to make it compatible with freebsd again. Any contribution are very welcome.

**Comment by wolrah** [comment]
If I have success I will definitely contribute whatever I come up with.  Still working on it.  By chance do you know the last version you can say for sure did work?  I figure my best approach is going to be to start from there and bisect to try to work on one issue at a time.

**Comment by voipmonitor** [comment]
Unfortunately I cannot remember

Dne 21. 9. 2016 22:16 napsal uživatel "Sean Harlow" <
notifications@github.com>:

**Comment by bu7cher** [comment]
Hello, I have a [port](https://people.freebsd.org/~ae/voipmonitor.tar.gz) to build the FreeBSD package that we use at work, it is a bit hackish and contains several patches to fix the build. It would be nice, if someone of your developers team take a look to these patches (they are in files/ directory).

**Comment by voipmonitor** [comment]
would you please commit it to your own branch? Is it based on the latest sources? (we did some progress with the porting to freebsd recently)

**Comment by bu7cher** [comment]
> would you please commit it to your own branch? Is it based on the latest sources? (we did some progress with the porting to freebsd recently)

I committed my changes and made the pull request. Thanks!
