### ISSUE TITLE
odbc error

### ISSUE THREAD

**Issue by eskornev** [voipmonitor/sniffer#38]
Just compiled version 17.4 and can not connect to psql via odbc.

Console output looks like this:
$sudo /usr/local/sbin/voipmonitor --config-file /etc/voipmonitor.conf --pid-file  /var/run/voipmonitorinitscript.pid -n -i eth0 -k 
Loading configuration from file /etc/voipmonitor.conf OK
voipmonitor version 17.4
voipmonitor[18773]: start voipmonitor version 17.4
local time 2016-10-26 15:43:29
voipmonitor[18773]: local time 2016-10-26 15:43:29
voipmonitor[18773]: detected rrdtool version 10308
voipmonitor[18773]: odbc query error:  ERROR: syntax error at or near "like";
Error while executing the query
voipmonitor[18773]: odbc query error:  ERROR: syntax error at or near "like";
...

Odbc test is successfull:
$ sudo isql -v voipmonitor voipmonitor
+---------------------------------------+
| Connected!                            |

Database remains clean, no tables.

Software versions:
unixODBC-devel-2.2.14-14.el6.x86_64
unixODBC-2.2.14-14.el6.x86_64

odbc.ini file:
[voipmonitor]
Description     = PostgreSQL
Driver          = PostgreSQL
Database        = voipmonitor
Server          = 10.0.X.X
Port            = 5432
Protocol        = 9.4
ReadOnly        = No

odbcinst.ini:
[PostgreSQL]
Description = ODBC for PostgreSQL
Driver      = /usr/pgsql-9.4/lib/psqlodbc.so
Setup       = /usr/lib/libodbcpsqlS.so
Driver64    = /usr/pgsql-9.4/lib/psqlodbc.so
Setup64     = /usr/lib64/libodbcpsqlS.so
FileUsage   = 1

**Comment by voipmonitor** [comment]
Hello, we are going to drop ODBC completely, it is not maintained now and not even tested for a long time.
