### ISSUE TITLE
jitter causing high levels of packet loss only if first packet not out-of-order

### ISSUE THREAD

**Issue by mkrokosz** [voipmonitor/sniffer#39]
When an rtp stream starts with an out-of-order first packet (with seq=0), any future packets which are out-of-order are **not** counted as packet loss.  However, if the first packet (with seq=0) is received properly, then future packets which are out-of-order (caused by jitter), are counted as packet loss.  

This can easily be reproduced by injecting jitter between two endpoints (sipp uac -> uas) using linux "tc" command.  For calls which have their first packet received late, there is no packet loss but for calls which have their first packet received as expected, there is large packet loss (because of the jitter causing packets out-of-order).

I tend to think the desired behavior for "packet loss" should not include packets received out-of-order since they could be handled by jitter buffers (as reflected by the MOS score).

Also, in both scenarios the MOS scores are the same and not impacted.

**Comment by mkrokosz** [comment]
Here are some logs while troubleshooting which shows the problem...

Dec 18 18:41:30 sipp_vm1 voipmonitor[26505]: **** **first_seq=0,** init_seq=3, probation_skipped=1, **out_of_order=445**, base_seq=1, **lost=447**, received=1745, cycles=2, max_seq=1746
Dec 18 18:41:30 sipp_vm1 voipmonitor[26505]: **** first_seq=0, init_seq=3, probation_skipped=1, out_of_order=445, base_seq=1, lost=447, received=1745, cycles=2, max_seq=1746
Dec 18 18:42:25 sipp_vm1 voipmonitor[26505]: **** first_seq=0, init_seq=2, probation_skipped=1, out_of_order=493, base_seq=2, lost=493, received=1745, cycles=0, max_seq=1746
Dec 18 18:42:25 sipp_vm1 voipmonitor[26505]: **** first_seq=0, init_seq=2, probation_skipped=1, out_of_order=493, base_seq=2, lost=493, received=1745, cycles=0, max_seq=1746
Dec 18 18:46:30 sipp_vm1 voipmonitor[26505]: **** **first_seq=1,** init_seq=4, probation_skipped=3, **out_of_order=470**, base_seq=4, **lost=0**, received=1745, cycles=0, max_seq=1748
Dec 18 18:46:30 sipp_vm1 voipmonitor[26505]: **** first_seq=1, init_seq=4, probation_skipped=3, out_of_order=470, base_seq=4, lost=0, received=1745, cycles=0, max_seq=1748
Dec 18 18:47:24 sipp_vm1 voipmonitor[26505]: **** first_seq=1, init_seq=3, probation_skipped=2, out_of_order=471, base_seq=3, lost=0, received=1748, cycles=0, max_seq=1751
Dec 18 18:47:24 sipp_vm1 voipmonitor[26505]: **** first_seq=1, init_seq=3, probation_skipped=2, out_of_order=471, base_seq=3, lost=0, received=1747, cycles=0, max_seq=1749

**Comment by voipmonitor** [comment]
Hi, this is known issue. The packet loss is counted according to RFC (you will see the same packet loss in wireshark which follows the same calculations). However MOS scoring uses jitterbuffer which is able to do reorder.

**Comment by voipmonitor** [comment]
Anyway - would you provide some pcap samples?
