### ISSUE TITLE
Is custom_headers thing broken?

### ISSUE THREAD

**Issue by Worldexe** [voipmonitor/sniffer#40]
Is custom_header handling broken or I just doing something wrong?

I set `custom_headers_cdr` option in my config (I see it can be set as `custom_headers` also); voipmonitor creates additional columns in `cdr_next` table, but does not populate them.

I checked the code - it seems writing them into `cdr_next` was obsoleted, and they should go into `cdr_custom_headers` instead, but that table does not get created and so this all does not work.

Is it really a bug or I am missing something?

My version is `voipmonitor version 17.14`, downloaded directly as binary from your website.

**Comment by voipmonitor** [comment]
Hi, we have changed the custom headers handling which is driven from the database now. we did not writen doc for this. You can control the custom headers in the GUI -> settings -> custom headers.

**Comment by Worldexe** [comment]
I am sorry, I do not use commercial GUI.
How can it be done via manual configuration? Should I create some table myself?

**Comment by viktorsperl** [comment]
Having the same issue, also using the sniffer only. The new fields in the cdr_next table are created, but all values are NULL.
