### ISSUE TITLE
What IDE to use to make some tiny changes in code?

### ISSUE THREAD

**Issue by EdClayton** [voipmonitor/sniffer#44]
We need to make a tiny change in SipHeader parsing.
Can you tell me how can I open project in any IDE and compile?
is there any documentation on this project to understand the structure  and classes?

Thank you

**Comment by voipmonitor** [comment]
Hi, there is no IDE to open the project and there is no documentation describing structures and classes. We can do development for you, please contact info@voipmonitor.org
