### ISSUE TITLE
How to Record All Calls even those which are answered by IVR on asterisk?

### ISSUE THREAD

**Issue by EdClayton** [voipmonitor/sniffer#45]
Two asterisks are connected by IAX2 Trunk , and voipmonitor records calls between SIP extensions,
but if an extensions dials an IVR extension on asterisk, no CDR is saved and voipmonitor does not record the call.
I guess it is because in this case there is no Ringing event generated by asterisk and directly 200 OK response is generated.
Is there any way to say voipmonitor to record all calls, even those which are routed to IVR.

**Comment by voipmonitor** [comment]
Hello, need to see pcap file.
