### ISSUE TITLE
Upgrade to 20.4.1: 29.08.2017 sniffer causes segfault

### ISSUE THREAD

**Issue by shido6** [voipmonitor/sniffer#46]
Upgrading central voipmonitor sniffer, web gui reports an incomplete configuration for remote sensors. Local sensor reports Connection refused.

Updated central server to use mirror_use_checksum = yes and mirror_require_confirmation = yes
Rebooted central server, everything seems to connect back up properly.

I didnt have these set before but with the upgrade I needed to turn it on. One of the sniffers had it enabled. I enabled it across all other sniffers and now the problem is gone.

**Comment by milon21** [comment]
hello,

do you have a core dump from this segfault ? Can you share the cfg of your central server, please ? Number of remote clients ? Architecture and OS ? 

Thanks.
