### ISSUE TITLE
pcap not found.

### ISSUE THREAD

**Issue by leftyb** [voipmonitor/sniffer#48]
Hi,

We are having some issues downloading some PCAP files. Although at the UI we can see that there is a pcap file available, and the link to download it is enabled, when trying to download the pcap we get following error:
` File 2017-10-13/13/46/[SIP|RTP|ALL|REG]/1507901477844.pcap not found`

Just to comment this specific error is not happening with all calls, but at some of them. At the moment we can not locate, to which calls we have that problem. It seems a bit random.

If possible to guide us, how to troubleshoot in order to understand why this is happening.

Thank you.

**Comment by milon21** [comment]
Hello,

it seems that it's a GUI problem. Please don't use github for gui's trouble. Use support@voipmonitor.org instead.

Thanks.

**Comment by leftyb** [comment]
Hi, 
I apologize, I will send an email.
Thank you.
