### ISSUE TITLE
Http Monitoring

### ISSUE THREAD

**Issue by leftyb** [voipmonitor/sniffer#49]
Hi,

Is it possible to monitor as well http traffic? IF possible, is there something that we need to enable at the sniffer configuration file? 
 
I can see at the UI, that there are some filters that can be applied for HTTP, so I guess that it is possible to monitor HTTP as well.

Thank you.

**Comment by voipmonitor** [comment]
Hi, 

the voipmonitor is able to corellate http to sip messages but we did it for one specific customer. Would you please describe what is your http exactly?

**Comment by leftyb** [comment]
Hi,

Our http, requests are not  correlated to any SIP traffic, they can be mainly RestAPI requests that we need to monitor. Something [like] (http://documentation.telestax.com/connect/api/calls-api.html). Or some other service intern-communication http requests, similar to the ones from the public RestAPI.

Thank you

**Comment by voipmonitor** [comment]
got it. voipmonitor is not able to do this.

**Comment by leftyb** [comment]
Thank you.

**Comment by leftyb** [comment]
Hi,
Just a quick question, what is this option about:

```
# enable monitoring IP traffic 
#ipaccount = no
#ipaccountport = 22
#ipaccountport = 80
#ipaccountport = 443
```

Thank you.

**Comment by voipmonitor** [comment]
its for counting traffic per IP address / port.
