### ISSUE TITLE
Compile on Espressobin running Armbian

### ISSUE THREAD

**Issue by markwiater** [voipmonitor/sniffer#58]
Hi, 

I'm trying to compile on an armbian based machine, configure has run successfsully but make doesn't know what to do.

root@espressobin:~/sniffer# uname -m
aarch64
root@espressobin:~/sniffer# uname -a
Linux espressobin 4.19.14-mvebu64 #5.69 SMP PREEMPT Thu Jan 10 12:03:52 CET 2019 aarch64 GNU/Linux

root@espressobin:~/sniffer# cat /etc/armbian-release 
# PLEASE DO NOT EDIT THIS FILE
BOARD=espressobin
BOARD_NAME="Espressobin"
BOARDFAMILY=mvebu64
VERSION=5.69
LINUXFAMILY=mvebu64
BRANCH=next
ARCH=arm64
IMAGE_TYPE=stable
BOARD_TYPE=conf
INITRD_ARCH=arm64
KERNEL_IMAGE_TYPE=Image

Is there any chance you'll consider updating the build environment to support this architecture?  Is there something more you need from me to assist?

Thanks

Mark

**Comment by voipmonitor** [comment]
Hi, can you allow ssh login so we can see it?

**Comment by markwiater** [comment]
I can do that, give me a few minutes to set that up.

**Comment by markwiater** [comment]
If you could pm me I can get you access to this machine

**Comment by voipmonitor** [comment]
send me email to info@voipmonitor.org please
