### ISSUE TITLE
Reactivate github releases when new sniffer versions are published.

### ISSUE THREAD

**Issue by joelsdc** [voipmonitor/sniffer#59]
Hello, 

I see here https://github.com/voipmonitor/sniffer/releases that at one point releases were being tagged, but nowadays they are not. 

Can you please tag the releases again so it is easy to integrate with automation tools?

Thank you!
Joel.

**Comment by voipmonitor** [comment]
Hi, any commit into the master branch can be considered as full new release.  Stick with the master branch and it should do what you need?
