### ISSUE TITLE
debian/docs fix raspbian readme definition

### ISSUE THREAD

**Issue by arvatoth-vcc** [voipmonitor/sniffer#64]
Hi,

There is a typo in debian/docs file (in develop branch): README_raspian.md

The correct filename is README_rasp**b**ian.md

Thank you

**Comment by voipmonitor** [comment]
Hi, 

in the latest develop branch and master branch the file is already README_raspian.md

**Comment by arvatoth-vcc** [comment]
Sorry, the problem is in the debian/docs file. After you renamed file to README_raspbian.md forgot to modify debian/docs file.

**Comment by voipmonitor** [comment]
I see it now. Fixed.
