### ISSUE TITLE
Commit broke automated installs

### ISSUE THREAD

**Issue by verticelo** [voipmonitor/sniffer#65]
The following commit broke our automated install environment, such as Ansible/Chef/Salt etc.

https://github.com/voipmonitor/sniffer/commit/b47397a0b34ae638b53691ff3b3d1b2af0b25357#diff-fbd9a43367ca2a7abeee7be783b3326b

Could you please provide a way to pass arguments to your install script so the Voipmonitor Sniffer can be installed via CLI without requiring user input?

We are a paying customer of Voipmonitor if that makes any difference.

**Comment by voipmonitor** [comment]
Hello, my college Milan will look at it and bring some solution to it.

**Comment by milon21** [comment]
Hello,

will be enough for you if I will add a special parameter e.g. --no-user-input into the install script ?

Thanks

**Comment by verticelo** [comment]
Yes, that would work. We replace the config file anyway with a file hosted on our provisioner so we just want to install the binary and then we setup the config via our automated installer.
