### ISSUE TITLE
WebRTC or video codec support 

### ISSUE THREAD

**Issue by John-GITtesting** [voipmonitor/sniffer#73]
Hi Team,

Do you have any plans to add support for video codecs in the future?

Thanks,

John.

**Comment by voipmonitor** [comment]
Hi, 

webrtc is supported but voice only. We have almost no demand for video features so we do not plan it in near future (unless someone will pay for it)

**Comment by John-GITtesting** [comment]
Hi, 

Thanks for the reply and no worries. 

John.
