### ISSUE TITLE
Project structure

### ISSUE THREAD

**Issue by kvishnivetsky** [voipmonitor/sniffer#74]
Hi!

I have some questions:
1. Is this reporsitory an "official" one, becuase there are different other repos in *.md files refrenced.
2. What is branching/tagging policy? Which branch/tag is "stable"? How to determine a branch of paticular version?

**Comment by voipmonitor** [comment]
Hi, 

master branch is stable, develop branch is development. There are no other branches or tags.

**Comment by kvishnivetsky** [comment]
Thanks!
