### ISSUE TITLE
Error running the keylogger test

### ISSUE THREAD

**Issue by MichaelSwann** [voipmonitor/sniffer#80]
Hi, I am getting the following error while running the keylogger test.

```
env SSLKEYLOG_UDP='127.0.0.1:1234' LD_PRELOAD="/usr/local/src/voipmonitor-git/tools/ssl_keylogger/sslkeylog.so" openssl
openssl: symbol lookup error: /usr/local/src/voipmonitor-git/tools/ssl_keylogger/sslkeylog.so: undefined symbol: __gxx_personality_v0
```

**Operation System:** Ubuntu 20.04
**OpenSSL Version:** OpenSSL 1.1.1f

For comparison, I followed the same steps against a Centos server and the test worked. Sadly all our production servers are running Ubuntu.

Thanks in advance.

**Comment by voipmonitor** [comment]
Hi, 

can you edit Makefile and change CC=gcc to CC=g++ and let me know if it works

**Comment by MichaelSwann** [comment]
That worked.

Thanks for the prompt feedback.
