### ISSUE TITLE
Turn off cachedir

### ISSUE THREAD

**Issue by konstantin-sancom** [voipmonitor/sniffer#85]
Hi!
is it possible to force sniffer not to use `cachedir`?

I tryed:
1. Set `cachedir` option to empty `cachedir = ` in configuration file.
2. Not to set `cachedir` option in configuration file.
3. Run sniffer with `--cachedir=''` argument.
Result is the same - sniffer create `/dev/shm/voipmonitor` on startup.

**Comment by voipmonitor-petr** [comment]
Hello,

mysql's settings have greater priority then settings in a file, you can disable lload settings from db by mysqlloadconfig=no in /etc/voipmonitor.conf 
(I was not able to replicate it - I have no /dev/shm/voipmonitor created.
