### ISSUE TITLE
Save Proxy-Auth / Authorization Headers

### ISSUE THREAD

**Issue by pbooysen** [voipmonitor/sniffer#86]
Hi,

Is it possible to save the Auth username located in the SIP Auth headers using the sniffer? 

Regards

**Comment by prosper86** [comment]
Hi. Did you get the solution?

**Comment by pbooysen** [comment]
Hi, unfortunately not. We are currently looking for a way around this limitation.

**Comment by prosper86** [comment]
Bro do you know how to use json header to get proxy credentials
