### ISSUE TITLE
saveaudio g711a vs g722

### ISSUE THREAD

**Issue by Dropicx** [voipmonitor/sniffer#91]
Hi there,
I'm exploring that my g722 calls are playable via WebGUI but I cannot find them in the spool directory. When I compare it to g711a, the calls are getting normally saved in the spool directory. I'm testing with SIPp and maybe it's my g722 sample that produces this problem but why can I play it via WebGUI and it's not saved in the directory? The voipmonitor.conf don't differs g711a and g722, so both should be saved as .wav as I thought.

Edit: I will try it with this tutorial for now: https://www.voipmonitor.org/doc/Create_audio_from_packet_dumps_located_in_a_spooldir

RE: Edit: The tutorial works with g722. Of course, it's more efficient that the wav's aren't recorded live. So creating the audio files afterwards is better and I will do it like that. saveaudio=no...

**Comment by voipmonitor** [comment]
Hi, 

sniffer can decode only G711. G22 is decoded only by the GUI on demand.
