### ISSUE TITLE
Record only incoming RTP

### ISSUE THREAD

**Issue by Dropicx** [voipmonitor/sniffer#92]
Hey is it possible to save only the incoming RTP into the pcap files? 
I aim to record the incoming audio but not the own outgoing audio.

Thank you.

**Comment by milon21** [comment]
Hello,

If I understand the question correctly then you want to store only one direction of the call's rtp streams. Unfortunately it's not possible in current sensor.

**Comment by Dropicx** [comment]
Yes you understood correctly. Thank you for your answer.

--Closed
